-- rpodder initial schema for PostgreSQL
-- All IDs are UUIDv7 (time-sorted), generated by the application layer.

-- =========================================================================
-- Users
-- =========================================================================

CREATE TABLE IF NOT EXISTS users (
    id          UUID PRIMARY KEY,
    username    VARCHAR(150) NOT NULL,
    password_hash TEXT NOT NULL,
    email       VARCHAR(254),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (LOWER(username));
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (LOWER(email)) WHERE email IS NOT NULL;

-- =========================================================================
-- Sessions
-- =========================================================================

CREATE TABLE IF NOT EXISTS sessions (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(128) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions (token);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions (expires_at);

-- =========================================================================
-- Sync Groups
-- =========================================================================

CREATE TABLE IF NOT EXISTS sync_groups (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- Devices
-- =========================================================================

CREATE TABLE IF NOT EXISTS devices (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id       VARCHAR(64) NOT NULL,   -- user-assigned uid (e.g. "my-phone")
    caption         VARCHAR(256) NOT NULL DEFAULT '',
    device_type     VARCHAR(16) NOT NULL DEFAULT 'other',
    sync_group_id   UUID REFERENCES sync_groups(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_device_type CHECK (device_type IN ('desktop','laptop','mobile','server','tablet','other'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_devices_user_uid ON devices (user_id, device_id);

-- =========================================================================
-- Podcasts
-- =========================================================================

CREATE TABLE IF NOT EXISTS podcasts (
    id                      UUID PRIMARY KEY,
    title                   VARCHAR(1000) NOT NULL DEFAULT '',
    description             TEXT NOT NULL DEFAULT '',
    link                    VARCHAR(2048),
    language                VARCHAR(16),
    logo_url                VARCHAR(2048),
    author                  VARCHAR(512),
    subscribers             BIGINT NOT NULL DEFAULT 0,
    episode_count           BIGINT NOT NULL DEFAULT 0,
    last_update             TIMESTAMPTZ,
    update_interval_hours   INTEGER NOT NULL DEFAULT 168,  -- 7 days
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_podcasts_subscribers ON podcasts (subscribers DESC);
CREATE INDEX IF NOT EXISTS idx_podcasts_last_update ON podcasts (last_update);
CREATE INDEX IF NOT EXISTS idx_podcasts_language ON podcasts (language) WHERE language IS NOT NULL;

-- Full-text search index (PostgreSQL-specific)
ALTER TABLE podcasts ADD COLUMN search_vector TSVECTOR;

CREATE INDEX IF NOT EXISTS idx_podcasts_search ON podcasts USING GIN (search_vector);

CREATE OR REPLACE FUNCTION podcasts_search_trigger() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        SETWEIGHT(TO_TSVECTOR('simple', COALESCE(NEW.title, '')), 'A') ||
        SETWEIGHT(TO_TSVECTOR('simple', COALESCE(NEW.author, '')), 'B') ||
        SETWEIGHT(TO_TSVECTOR('simple', COALESCE(NEW.description, '')), 'C');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

CREATE TRIGGER IF NOT EXISTS trg_podcasts_search
    BEFORE INSERT OR UPDATE OF title, author, description ON podcasts
    FOR EACH ROW EXECUTE FUNCTION podcasts_search_trigger();

-- =========================================================================
-- Podcast URLs
-- =========================================================================

CREATE TABLE IF NOT EXISTS podcast_urls (
    id          UUID PRIMARY KEY,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,
    url         VARCHAR(2048) NOT NULL,
    "order"     INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT uq_podcast_urls_url UNIQUE (url),
    CONSTRAINT uq_podcast_urls_order UNIQUE (podcast_id, "order")
);

CREATE INDEX IF NOT EXISTS idx_podcast_urls_podcast ON podcast_urls (podcast_id);

-- =========================================================================
-- Episodes
-- =========================================================================

CREATE TABLE IF NOT EXISTS episodes (
    id          UUID PRIMARY KEY,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,
    guid        VARCHAR(512),
    title       VARCHAR(1000) NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    link        VARCHAR(2048),
    released    TIMESTAMPTZ,
    duration    BIGINT,         -- seconds
    filesize    BIGINT,         -- bytes
    mimetype    VARCHAR(128),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_episodes_podcast ON episodes (podcast_id);
CREATE INDEX IF NOT EXISTS idx_episodes_podcast_released ON episodes (podcast_id, released DESC);
CREATE INDEX IF NOT EXISTS idx_episodes_guid ON episodes (podcast_id, guid) WHERE guid IS NOT NULL;

-- =========================================================================
-- Episode URLs
-- =========================================================================

CREATE TABLE IF NOT EXISTS episode_urls (
    id          UUID PRIMARY KEY,
    episode_id  UUID NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    url         VARCHAR(2048) NOT NULL,
    "order"     INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT uq_episode_urls_url_podcast UNIQUE (url),
    CONSTRAINT uq_episode_urls_order UNIQUE (episode_id, "order")
);

CREATE INDEX IF NOT EXISTS idx_episode_urls_episode ON episode_urls (episode_id);

-- =========================================================================
-- Subscriptions (current state)
-- =========================================================================

CREATE TABLE IF NOT EXISTS subscriptions (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id   UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,
    ref_url     VARCHAR(2048) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_subscriptions UNIQUE (user_id, device_id, podcast_id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_device ON subscriptions (user_id, device_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_podcast ON subscriptions (podcast_id);

-- =========================================================================
-- Subscription Changes (append-only history for delta sync)
-- =========================================================================

CREATE TABLE IF NOT EXISTS subscription_changes (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id   UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,
    action      VARCHAR(16) NOT NULL,
    ref_url     VARCHAR(2048) NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_sub_action CHECK (action IN ('subscribe','unsubscribe'))
);

CREATE INDEX IF NOT EXISTS idx_subchanges_user_device_ts ON subscription_changes (user_id, device_id, timestamp);

-- =========================================================================
-- Episode Actions (append-only)
-- =========================================================================

CREATE TABLE IF NOT EXISTS episode_actions (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id       UUID REFERENCES devices(id) ON DELETE SET NULL,
    episode_id      UUID NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    action          VARCHAR(16) NOT NULL,
    podcast_ref_url VARCHAR(2048),
    episode_ref_url VARCHAR(2048),
    started         INTEGER,        -- seconds from start (play only)
    position        INTEGER,        -- seconds from start (play only)
    total           INTEGER,        -- total duration in seconds (play only)
    timestamp       TIMESTAMPTZ NOT NULL,  -- client-provided
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_ep_action CHECK (action IN ('download','play','delete','new'))
);

CREATE INDEX IF NOT EXISTS idx_epactions_user_ts ON episode_actions (user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_epactions_user_device ON episode_actions (user_id, device_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_epactions_user_episode ON episode_actions (user_id, episode_id);
-- Deduplication index: same user+episode+device+action+position should not be stored twice
CREATE UNIQUE INDEX IF NOT EXISTS idx_epactions_dedup
    ON episode_actions (user_id, episode_id, COALESCE(device_id, '00000000-0000-0000-0000-000000000000'), action, timestamp);

-- =========================================================================
-- User Settings (key-value per scope)
-- =========================================================================

CREATE TABLE IF NOT EXISTS user_settings (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scope       VARCHAR(16) NOT NULL,
    scope_id    UUID,           -- NULL for 'account' scope
    settings    JSONB NOT NULL DEFAULT '{}',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_settings_scope CHECK (scope IN ('account','device','podcast','episode'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_settings_scope ON user_settings (user_id, scope, COALESCE(scope_id, '00000000-0000-0000-0000-000000000000'));

-- =========================================================================
-- Tags
-- =========================================================================

CREATE TABLE IF NOT EXISTS tags (
    id          UUID PRIMARY KEY,
    tag         VARCHAR(128) NOT NULL,
    source      VARCHAR(8) NOT NULL,
    user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,

    CONSTRAINT chk_tag_source CHECK (source IN ('feed','user')),
    CONSTRAINT uq_tags UNIQUE (tag, source, user_id, podcast_id)
);

CREATE INDEX IF NOT EXISTS idx_tags_podcast ON tags (podcast_id);
CREATE INDEX IF NOT EXISTS idx_tags_tag ON tags (tag);

-- =========================================================================
-- Podcast Lists
-- =========================================================================

CREATE TABLE IF NOT EXISTS podcast_lists (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title       VARCHAR(256) NOT NULL,
    slug        VARCHAR(256) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_podcast_lists UNIQUE (user_id, slug)
);

CREATE TABLE IF NOT EXISTS podcast_list_entries (
    id          UUID PRIMARY KEY,
    list_id     UUID NOT NULL REFERENCES podcast_lists(id) ON DELETE CASCADE,
    podcast_id  UUID NOT NULL REFERENCES podcasts(id) ON DELETE CASCADE,
    "order"     INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT uq_podcast_list_entries UNIQUE (list_id, podcast_id)
);

CREATE INDEX IF NOT EXISTS idx_plist_entries_list ON podcast_list_entries (list_id, "order");

-- =========================================================================
-- Chapters (user-defined)
-- =========================================================================

CREATE TABLE IF NOT EXISTS chapters (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    episode_id      UUID NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    start_sec       INTEGER NOT NULL,
    end_sec         INTEGER NOT NULL,
    label           VARCHAR(512) NOT NULL DEFAULT '',
    advertisement   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chapters_user_episode ON chapters (user_id, episode_id);

-- =========================================================================
-- Favorite Episodes
-- =========================================================================

CREATE TABLE IF NOT EXISTS favorite_episodes (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    episode_id  UUID NOT NULL REFERENCES episodes(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_favorites UNIQUE (user_id, episode_id)
);

-- =========================================================================
-- Categories
-- =========================================================================

CREATE TABLE IF NOT EXISTS categories (
    id          UUID PRIMARY KEY,
    tag         VARCHAR(128) NOT NULL UNIQUE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
